### PR TITLE
fixed quoting of comments

### PR DESCRIPTION
**Pull request by mchf**
fixed issue when # comment --> # "comment" on write. Thanks to jsuchome.

### CODE REVIEW

**Comment by jsuchome** [comment]
Values are unquoted on write, this does not look right to me:

-ROOT_USES_LANG="ctype"
+ROOT_USES_LANG=ctype

**Comment by mchf** [comment]
what is invalid? echo "ctype" == echo ctype Different syntax, semantics is the same.

**Comment by jsuchome** [comment]
I'm not saying syntax is wrong, but why should it change whan nothing else (= the value) does not?
This way, files get modified even if no value was changed.

**Comment by mchf** [comment]
Bcs you every time reads whole file and then writes it back. This is price for resolving quoting at low level. We can define some default quotes, it solves the problem partially.

**Comment by jsuchome** [comment]
I think it would be better. Josef, what do  you think?

**Comment by jreidinger** [comment]
Well, at first I think that it is missing feature of augeas. It would be nice to store also raw content and if value not change then don't change it at all.
For quoting. I agree with Jiri, that we should use default quoting. It is much more common to use quotes "" in sysconfig. so it should be default. Rewritting values if we don't change semantics doesn't look for me like a big problem and if it was, then it should be changed in augeas, not in gloves or agents.

**Comment by mchf** [comment]
I think that single quote should be better choice as all bultin escaping functions I saw use it. However, when adding quotes we come to same problem from opposite side if a user use unquoted value. Moreover, I think that unquoting should not be responsibility of augeas, as it is general config file parser and values should be opaque for it. Definitely, in present situation augeas has no means to resolve unquoting properly.

**Comment by jreidinger** [comment]
Well, I forget that we do both quoting and unquoting. I think that we should detect if we make a change value and if not, then use same value ( so do not modify it ). Of course if we make change, then do it properly. Single quotes looks like good solution as it solve some situation, but not everything. Consider this example:

```
VAL1="http://dest.com"
VAL2="${VAL1}/tmp"
```

this will be broken if we change it to

```
VAL1='http://dest.com'
VAL2='${VAL1}/tmp'
```

**Comment by mchf** [comment]
I've talked about situation when adding default quotes is required. It means a value without special chars (<=> situation when current escaping function doesn't add any quotes - that is the case which started the discussion) . Otherwise you can find an example against double quotes too. Consider:

```
VAL1='$10'
VAL2=${VAL1}
```

and

```
VAL1="$10"
VAL2=${VAL1}
```

Values with special chars inside must pass escaping procedure and no default quoting should be considered.

**Comment by jsuchome** [comment]
Josef, do you think your example is actually valid? I think Michal is right that the value must be prepared for this.

As for default quote type, I would prefer double quotes just because they are currenly used over most (if not all) our sysconfig files.

**Comment by jsuchome** [comment]
Michal, I guess your new changes should change config_agent-country/test/data2/etc/sysconfig/\* as well... ?

**Comment by mchf** [comment]
this patch implements "preserving old values", so it would change nothing of its own accord

**Pull request merged**
