### PR TITLE
agent for accessing sysconfig files

### PR DESCRIPTION
**Pull request by mchf**
s/yast++/gloves/ and related done too.
uses c extension for unquoting. The extension is slightly modified GLib2 method for unquoting (licensed under LGPL 2.1)

### CODE REVIEW

**Comment by jreidinger** [comment]
Well, I think it was too early to accept such patch.
For me it is overengineering.

We use now ruby 1.8.330 which already have inside function to escape shell ( sorry for not mention it earlier - see http://apidock.com/ruby/v1_8_7_330/Shellwords/shellescape ). So this whole escaping stuff is unnecessary code.
At second I don't like messing parameters with file path. I already do some changes to architecture and I think that it makes perfect sense to have it as parameter for initialization so something like
clock = SysconfigAgent.new '/etc/sysconfig/clock'
clock.read(params)
clock.write(value,params)

**Comment by mchf** [comment]
ok. I'll modify.

**Comment by jreidinger** [comment]
I already do it in @e8a8f84d581265ec80d009d85edcc292e79af17b
I just found that quoting is in ruby, but unquoting not. But still I think that whole dependency on glib is overkill, so I write there simple automate, that unquote string.

**Comment by mchf** [comment]
as I wrote ... there is not whole GLib. Thats the reason why I created the extension. It's only unquoting function and couple of macros.

**Comment by mchf** [comment]
as a note: I wrote about GLib gem. Glib C lib is of course required. However I thing, it is essential lib to linux, so no problem.

**Comment by jreidinger** [comment]
glib is gtk library and of course it have its own ruby bindings. So if we really need it we can require and not write own part. see https://github.com/ruby-gnome2/ruby-gnome2

**Comment by mchf** [comment]
ok. didn't know. Idea was to use some already implemented and working unquoting function, because I had many problems when debugging quoting for augeas. I wasn't able to run/find a bash command/tool which does unquoting. If you know any such tool, I would suggest to reuse it instead of own implementation.

**Comment by jreidinger** [comment]
Problem is that glib unquote also doesn't work, because unquoting is much more difficult task then quoting. GLib unquote can unquote only strings quoted by quote function, but sysconfig doesn't pass it ( lets try sysconfig that doesn't have quoted arguments like /etc/sysconfig/ulimit. Then glib method fail. So I welcome if we found good enough method public available if it doesn't add big dependency, but I don't see it.

**Pull request merged**
